name: BrewUpdate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version number (in 3.x.x format)'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest

    steps:
      - uses: mislav/bump-homebrew-formula-action@v3.2
        with:
          create-pullrequest: false
          formula-name: sass
          formula-path: Formula/sass.rb
          base-branch: main
          tag-name: ${{ github.event.inputs.version }}
          homebrew-tap: jackhamilton/homebrew-sass
          download-url: https://github.com/jackhamilton/sass-rs/releases/download/${{ steps.extract-version.outputs.tag-name }}/sass-mac.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_TOKEN }}
